[project]
name = "StickFig2Pose"
version = "0.1.0"
description = "An experimental project for generating poses from stick figure drawings."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
